version: "3.9"
services:
  web:
    container_name: django_spa_comments
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: ./django_spa_comments/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: bash -c "python ./django_spa_comments/manage.py migrate &&
                      python ./django_spa_comments/manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app

    environment:
      REDIS_URL: redis://redis
      DB_HOST: postgres
      POSTGRES_DB: "django_spa_comments"
      POSTGRES_USER: "django_spa_comments"
      POSTGRES_PASSWORD: "pass"
      SECRET_KEY: 123

  frontend:
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./react_spa_comments/comments/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - web

  redis:
    container_name: django_spa_comments_redis
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  postgres:
    container_name: django_spa_comments_postgres
    image: postgres:13.8
    environment:
      POSTGRES_DB: "django_spa_comments"
      POSTGRES_USER: "django_spa_comments"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U django_spa_comments -d django_spa_comments" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
